---
title: "John Hopkins Lessons"
author: "Tevin Sharp"
date: "2025-01-13"
output: html_document
---
### Vectors can only contain elements of the same type; ie strings, booleans, ints, etc
```{r}
#Initializes a numeric vector with a length of 10. Uses 0s as default values
v <- vector("numeric",length=10)

#Alternative way to create vector
v2 <- c(1,2,3,4,5)

print(v2)
```

###Lists can contain mixed objects
```{r}
l <- list(1,2,3,4,5)

print(l)

print(l[[2]])
```

###Matrices are vectors with a dimension attribute.The dimension attribute is itself an integer vector of length 2 (nrow,ncol)
```{r}
m <- matrix(nrow=2,ncol=3)
m
dim(m)
attributes(m)


m2 <- matrix(1:6,nrow=2,ncol=3)
m2

# You can also convert a vector to a matrix by adding dimensions with them dim function
m3 <- c(1,2,3,4)

dim(m3) <- c(2,2)

m3

# C bind and R bind are also popular ways to make matrices
x <- 1:5
y <- 10:14

length(y)
cbind(x,y)

rbind(x,y)
```


```{r}
# Factors used to represent categorical data. 

x <- factor(c("Yes",'No',"Yes",'No',"Yes",'No'))

x

table(x)

unclass(x)

# You can customize the order of the levels by specifying it in the factor function

x <- factor(c("Yes",'No',"Yes",'No',"Yes",'No'), 
            levels = c('Yes','No'))
x

```

```{r}
y <- data.frame(foo = 1:3, bar = c('a','b','c'),test = c(1,2,34))

y

nrow(y)
ncol(y)
```
```{r}
#R objects can have names

# Vectors:
x <- 1:3
names(x) <- c('This','is','Name')

x

# Lists
y <- list(a = 1, b = 2, c = 3, d= 10)
y


# Matrices
m <- matrix(1:4, nrow = 2, ncol = 2)
dimnames(m) <- list(c("a","b"),c("c","d"))

m
```
```{r}
# Subsetting

x <- c("a","b","c","d","e")

#  [ always returns an object of the same class as the original; can be used to select more than one element 

x[1] # prints a character vector with the single character "a" 
x[1:3] # prints a character vector with 3 characters
x[x > "a"]

u <- x > "a"
u

y <- list(foo=1:4, bar = 0.6)
y[1] # returns a list with the values of foo

# [[ is used to extract elements of a list or a data frame; it can be used to extract a single element and the class of the returned object will not necessarily be a list or data frame. Also can only use computed names with double brackets

y[[1]] # returns the sequence 1 2 3 4 (Not a list)

#  $ is used to extract elements of a list or data frame by name; semantics are similar to that of [[.

y$foo

# Subsetting multiple elements of a list (Can only use single brackets)
x[c(1,3)]

```


